### ISSUE TITLE
Problem encountered when using save_obj

### ISSUE THREAD

**Issue by minghaoPA** [hiroharu-kato/neural_renderer#21]
Hi there,

I am using your save_obj function, expecting to save the .obj as well as its texture generated from your model.

And what I added is only a straightforward line in example3.py, which is 

neural_renderer.save_obj('result.obj', model.vertices[0], model.faces[0], cf.tanh(model.textures[0]).array) 

Since I noticed you initialized the textures, vertices and faces with the first dimension of 1 as a batch size, I just get rid of this first dimension by indexing with 0.

The problem is I didn't get a reasonable .png from texture, in result an odd textured obj when showing in my meshlab software, and it differs a lot when comparing with the gif result. I provided what I got below in a zip file. Looking forward for any suggestions.

Thanks a lot!

 
![example3_result](https://user-images.githubusercontent.com/40280572/56072560-3f74e080-5d4d-11e9-9260-7e88f588f1e1.gif)
[save_obj_result.zip](https://github.com/hiroharu-kato/neural_renderer/files/3075591/save_obj_result.zip)

**Comment by minghaoPA** [comment]
And a screenshot for textured obj is:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/40280572/56072879-95975300-5d50-11e9-8966-203b9a43d566.png">

**Comment by logicsh** [comment]
Have you solved it now?and how
thanks for answering!

**Comment by Anannyap7** [comment]
I am encountering the same issue! Would love to know what you did to resolve this?
