### ISSUE TITLE
How to use it with python3.6 and pytorch1.5.0?

### ISSUE THREAD

**Issue by tjusxh** [hiroharu-kato/neural_renderer#31]
I am using the pytorch_geometric library, which requires python3.6 and pytorch1.5.0. Could I use it under python3.6 and pytorch1.5.0? How to do it?

**Comment by tjusxh** [comment]
I resolve the question by replacing AT_CHECK with TORCH_CHECK to support pytorch1.5.

**Comment by tjusxh** [comment]
I resolve the question by replacing AT_CHECK with TORCH_CHECK to support pytorch1.5.

**Comment by tiexuedanxin** [comment]
> I resolve the question by replacing AT_CHECK with TORCH_CHECK to support pytorch1.5.

hello, Could you tell me where to replacing AT_CHECK with TORCH_CHECK
