### ISSUE TITLE
GPU requirement

### ISSUE THREAD

**Issue by nitish11** [hiroharu-kato/neural_renderer#4]
Hi,

Is GPU mandatory for this project?
https://github.com/hiroharu-kato/neural_renderer/blob/master/examples/example3.py#L68

What is the parameter if I wanted to run on CPU?

**Comment by hiroharu-kato** [comment]
Currently, this code has no CPU implementation.
Since CPU implementation would be probably too slow for practical usage, we do not plan to support CPU.
