### ISSUE TITLE
Ghost texture problem

### ISSUE THREAD

**Issue by czw0078** [hiroharu-kato/neural_renderer#8]
I tested this wonderful renderer with a [coffee mug model](http://auburn.edu/~czw0078/issue_07_31/mug_model_example.zip) and it looks great! I built the model with software [Blender](https://www.blender.org/) by myself. 

However, when I compared it with the result below from OpenGL renderer (software Preview on Mac), I noticed that there were some "ghost" textures on the surface of the object in the result from neural mesh renderer (the result above):
![](http://auburn.edu/~czw0078/issue_07_31/opengl_version_mug.png)

To determine the cause of the ghost textures, I also called the save_obj function to save the loaded mesh (coffee mug). Here is how the saved model looks in the OpenGL (Preview software on Mac):
![figure_5](https://user-images.githubusercontent.com/21988239/44507042-b3536300-a66e-11e8-9735-204eecbbfa0b.png)

The result looks correct, except (a) the blurry texture (I think due to the `texture_size_out=16` not being as large as the size of textures tensor `texture_size x texture_size x texture_size = 4 x 4 x4 = 64` ); and (b) the minor flipping issue. But we do not see any ghost problem here.

Here is the Chainer code I used to call  `save_obj`:

```
import chainer
import numpy as np
import scipy.misc
import neural_renderer

renderer = neural_renderer.Renderer()

vertices, faces, textures = neural_renderer.load_obj( '/home/chengfei/projects/test_coffe_mug/straight.obj', load_texture=True, texture_size=16)

neural_renderer.save_obj('/home/chengfei/projects/test_coffe_mug/chainer_save.obj', vertices, faces, textures)
```

To further investigate the problem, I also rendered the same model renders with varying `texture_size` in the neural mesh renderer

texture_size = 4
![iterm2 04 out3](https://user-images.githubusercontent.com/21988239/44507937-11357a00-a672-11e8-94f3-c0df495d64ad.png)
texture_size = 8
![iterm2 08 out3](https://user-images.githubusercontent.com/21988239/44507944-1d213c00-a672-11e8-806c-b553579a9607.png)
texture_size = 16
![iterm2 16 out3](https://user-images.githubusercontent.com/21988239/44507954-26120d80-a672-11e8-8102-9b235ed76076.png)

You may notice that the larger the texture_size is, the sharper the textures look, also the more obvious ghosts appear.  Hope it can give you some insights on this bug.

I have also observed the same issue with at least 5 other models (which have image textures) downloaded online (e.g. from 3D Warehouse). I did not this issue in models with solid-color textures (i.e. textures defined only by .mtl files without any images).

@hiroharu-kato  Do you have any thoughts? I would greatly appreciate any pointers/ideas that you have. Thanks!

FYI. The same problem appears with the PyTorch version of this renderer. [Issue link](https://github.com/daniilidis-group/neural_renderer/issues/11).

**Comment by hiroharu-kato** [comment]
Sorry for fixing the problem.

I investigated the code using the mug model, and found that there is a bug in load_obj(). The image below is rendered after fixing the bug. The ghost has been erased.

![tmp](https://user-images.githubusercontent.com/15853190/45800677-98ffba00-bcec-11e8-8765-a776a4388a94.png)

This image is generated by the code below.

```
import neural_renderer
import cupy as cp
v, f, t = neural_renderer.load_obj('./ghost/straight.obj', load_texture=True, texture_size=8)
renderer = neural_renderer.Renderer()
# renderer.eye = [-2.73, 0, 0]

# t[2927:2930] = 0
v = cp.array(v)
f = cp.array(f)
t = cp.array(t)
images = renderer.render(v[None, :], f[None, :], t[None, :])
import scipy
scipy.misc.imsave('tmp.png', images[0].transpose((1, 2, 0)).data.get())
```

Thank you for reporting the problem!
